/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;
import requirements.OS;
import requirements.Process;
import structures.ProcessType;
import javax.swing.JOptionPane;
import SchedulerTechniques.StrategyScheduler;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import requirements.Process;

import requirements.Scheduler;
import structures.ProcessType;


/**
 *
 * @author rtkn0_z8ls
 */
public class PanelPrincipal extends javax.swing.JFrame {
    private File selectedFile;
    private OS os; // Referenciamos a nuestro OS
    
    private DefaultTableModel modeloTablaListos = new DefaultTableModel(
            new Object[][]{}, new String[]{"ID", "NAME", "STATE", "PC", "MAR"}
        );

        private DefaultTableModel modeloTablaBloqueados = new DefaultTableModel(
                new Object[][]{}, new String[]{"ID", "NAME", "STATE", "PC", "MAR"}
        );

        private DefaultTableModel modeloTablaTerminados = new DefaultTableModel(
                new Object[][]{}, new String[]{"ID", "NAME", "STATE", "PC", "MAR"}
        );

        private DefaultTableModel modeloTablaSupendido = new DefaultTableModel(
                new Object[][]{}, new String[]{"ID", "NAME", "STATE", "PC", "MAR"}
        );
    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal(OS os) { 
        this.os = os;
        this.setVisible(true);
        initComponents();
        colaSupendidos.setModel(modeloTablaSupendido);
        colaListos.setModel(modeloTablaListos);
        colaBloqueado.setModel(modeloTablaBloqueados);
        colaOut.setModel(modeloTablaTerminados);
        
     // 1. Poblar el JComboBox de Politicas de Planificacion
        String[] Politicas = { 
        "Round Robin", 
        "FCFS", 
        "SJF", 
        "SRT", 
        "HRRN", 
        "FB" 
        };
        PoliticaName.setModel(new javax.swing.DefaultComboBoxModel<>(Politicas));
        
         // 2. Poblar el JComboBox de Tipos de Proceso
        String[] TipoProceso = { 
            "CPU-Bound", 
            "I/O-Bound"
        };
        TypeProcess.setModel(new javax.swing.DefaultComboBoxModel<>(TipoProceso));
    }
        

        
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        instrucciones = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        ciclo = new javax.swing.JLabel();
        Spinnerciclo = new javax.swing.JSpinner();
        quantum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreProceso = new javax.swing.JTextField();
        randomProcess = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cargarDatos = new javax.swing.JButton();
        GuardarPlanificacion = new javax.swing.JButton();
        CantidadInstrucciones = new javax.swing.JSpinner();
        PoliticaName = new javax.swing.JComboBox<>();
        TypeProcess = new javax.swing.JComboBox<>();
        ciclo1 = new javax.swing.JLabel();
        ciclo2 = new javax.swing.JLabel();
        ciclo3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CyclesIO = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        IniciarProceso = new javax.swing.JButton();
        Priory = new javax.swing.JSpinner();
        cargarFile = new javax.swing.JButton();
        CyclesEx = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Listo = new javax.swing.JLabel();
        Bloqueados = new javax.swing.JLabel();
        Finalizados = new javax.swing.JLabel();
        Listo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        colaSupendidos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        colaListos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        colaBloqueado = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        colaOut = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        jPanel3.setBackground(new java.awt.Color(245, 247, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(156, 209, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Proceso");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        titulo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        titulo.setText("Simulador de Procesos ");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        instrucciones.setBackground(new java.awt.Color(0, 0, 0));
        instrucciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        instrucciones.setText("N. de Instrucciones:");
        jPanel2.add(instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        tipo.setBackground(new java.awt.Color(0, 0, 0));
        tipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipo.setText("Tipo:");
        jPanel2.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        ciclo.setBackground(new java.awt.Color(0, 0, 0));
        ciclo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo.setText("generar excepcion");
        jPanel2.add(ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 120, -1));

        Spinnerciclo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        Spinnerciclo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Spinnerciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 170, 25));

        quantum.setBackground(new java.awt.Color(0, 0, 0));
        quantum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.add(quantum, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 179, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Duracion del ciclo Ejec.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        NombreProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProcesoActionPerformed(evt);
            }
        });
        jPanel2.add(NombreProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, -1));

        randomProcess.setBackground(new java.awt.Color(0, 102, 255));
        randomProcess.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        randomProcess.setForeground(new java.awt.Color(255, 255, 255));
        randomProcess.setText("Cargar Aleatorios");
        randomProcess.setBorder(null);
        randomProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomProcessActionPerformed(evt);
            }
        });
        jPanel2.add(randomProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 120, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reiniciar Proceso");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 120, 30));

        cargarDatos.setBackground(new java.awt.Color(0, 102, 255));
        cargarDatos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        cargarDatos.setText("Cargar Datos");
        cargarDatos.setBorder(null);
        cargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(cargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 120, 30));

        GuardarPlanificacion.setBackground(new java.awt.Color(0, 102, 255));
        GuardarPlanificacion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        GuardarPlanificacion.setForeground(new java.awt.Color(255, 255, 255));
        GuardarPlanificacion.setText("Guardar");
        GuardarPlanificacion.setBorder(null);
        GuardarPlanificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarPlanificacionMouseClicked(evt);
            }
        });
        GuardarPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPlanificacionActionPerformed(evt);
            }
        });
        jPanel2.add(GuardarPlanificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 100, 30));

        CantidadInstrucciones.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10000, 1));
        CantidadInstrucciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CantidadInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 25));

        PoliticaName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PoliticaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoliticaNameActionPerformed(evt);
            }
        });
        jPanel2.add(PoliticaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 170, -1));

        TypeProcess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TypeProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeProcessActionPerformed(evt);
            }
        });
        jPanel2.add(TypeProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));

        ciclo1.setBackground(new java.awt.Color(0, 0, 0));
        ciclo1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo1.setText("satisfacer excepcion");
        jPanel2.add(ciclo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, -1));

        ciclo2.setBackground(new java.awt.Color(0, 0, 0));
        ciclo2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo2.setText("Cantidad de ciclos para ");
        jPanel2.add(ciclo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, -1));

        ciclo3.setBackground(new java.awt.Color(0, 0, 0));
        ciclo3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo3.setText("Cantidad de ciclos para ");
        jPanel2.add(ciclo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 160, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Politica");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        CyclesIO.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        CyclesIO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CyclesIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 170, 25));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 700, -1));

        IniciarProceso.setBackground(new java.awt.Color(102, 153, 255));
        IniciarProceso.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        IniciarProceso.setForeground(new java.awt.Color(255, 255, 255));
        IniciarProceso.setText("Iniciar Proceso");
        IniciarProceso.setBorder(null);
        IniciarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarProcesoActionPerformed(evt);
            }
        });
        jPanel2.add(IniciarProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 100, 30));

        Priory.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10000, 1));
        Priory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Priory, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 60, 25));

        cargarFile.setBackground(new java.awt.Color(0, 102, 255));
        cargarFile.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cargarFile.setForeground(new java.awt.Color(255, 255, 255));
        cargarFile.setText("Subir JSON/CSV");
        cargarFile.setBorder(null);
        cargarFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFileActionPerformed(evt);
            }
        });
        jPanel2.add(cargarFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 120, 30));

        CyclesEx.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        CyclesEx.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CyclesEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 170, 25));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 280));

        jPanel4.setBackground(new java.awt.Color(179, 220, 249));
        jPanel4.setFocusTraversalPolicyProvider(true);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Listo.setForeground(new java.awt.Color(102, 102, 102));
        Listo.setText("Listos");
        jPanel4.add(Listo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        Bloqueados.setForeground(new java.awt.Color(102, 102, 102));
        Bloqueados.setText("Bloqueados");
        jPanel4.add(Bloqueados, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 16, -1, 20));

        Finalizados.setForeground(new java.awt.Color(102, 102, 102));
        Finalizados.setText("Finalizados");
        jPanel4.add(Finalizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 15, -1, -1));

        Listo1.setForeground(new java.awt.Color(102, 102, 102));
        Listo1.setText("Suspendidos");
        jPanel4.add(Listo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Proceso en Ejecución");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 305, -1, -1));

        colaSupendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(colaSupendidos);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 240, 250));

        colaListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane3.setViewportView(colaListos);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 240, 250));

        colaBloqueado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane4.setViewportView(colaBloqueado);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 240, 250));

        colaOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(colaOut);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 240, 250));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 1120, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void randomProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomProcessActionPerformed
        
    }//GEN-LAST:event_randomProcessActionPerformed

    private void cargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosActionPerformed
         if (isEmpty()){
            //SE MUESTRA UN MENSAJE DE ERROR EN CASO DE QUE NO SE HAYA SELECCIONADO NINGUN ARCHIVO
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo primero");
         }else{
             String filePath = selectedFile.getAbsolutePath();
         }
         
    }//GEN-LAST:event_cargarDatosActionPerformed
    private boolean isEmpty(){
        return selectedFile  == null;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GuardarPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPlanificacionActionPerformed
        String politicaSeleccionada = (String) PoliticaName.getSelectedItem();
        StrategyScheduler estrategia;
        
        switch (politicaSeleccionada) {
            case "FCFS":
                estrategia = StrategyScheduler.FirstComeFirstServe;
                break;
            case "Round Robin":
                estrategia = StrategyScheduler.RoundRobin;
                break;
            case "SJF":
                estrategia = StrategyScheduler.SJF;
                break;
            case "SRT":
                estrategia = StrategyScheduler.SRT;
                break;
            case "HRRN":
                estrategia = StrategyScheduler.HRRN;
                break;
            case "FB":
                estrategia = StrategyScheduler.FB;
                break;
            default:
                System.out.println("Política desconocida, usando FCFS por defecto.");
                estrategia = StrategyScheduler.RoundRobin; // Valor por defecto
            }
        if (this.os != null) {
        // Accedemos al scheduler a través del OS y cambiamos la estrategia
        this.os.setSchedulingStrategy(estrategia);
        System.out.println("Estrategia de planificación cambiada a: " + politicaSeleccionada);
    }
    }//GEN-LAST:event_GuardarPlanificacionActionPerformed

    private void NombreProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProcesoActionPerformed

    private void PoliticaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoliticaNameActionPerformed
      
    }//GEN-LAST:event_PoliticaNameActionPerformed

    private void TypeProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeProcessActionPerformed
         // Obtener el tipo de proceos seleccionado
        String typeSelect = (String) TypeProcess.getSelectedItem();
        
        // Comprobar si es I/O-Bound
        boolean esIOBound = typeSelect.equals("I/O-Bound");
        /**
         *  Asumiendo que los componentes se llaman así:
            lblCyclesExcepcion.setVisible(esIOBound);
            txtCyclesExcepcion.setVisible(esIOBound);
            lblCyclesCompleteIO.setVisible(esIOBound);
            txtCyclesCompleteIO.setVisible(esIOBound);
         */
    }//GEN-LAST:event_TypeProcessActionPerformed

    private void IniciarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarProcesoActionPerformed
        try {
        // 1. LEER DATOS EN COMUN
        String nombre = NombreProceso.getText();
        int instrucciones = (Integer) CantidadInstrucciones.getValue();
        int priory = (Integer) Priory.getValue();
        
        // 2. LEER TIPO DE PROCESO SELECCIONADO
        String TypeSelected = (String) TypeProcess.getSelectedItem();
        
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para el proceso.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Process newProcess; // El proceso que vamos a crear
        
            // 3. DECIDIR QUÉ CONSTRUCTOR USAR
            if (TypeSelected.equals("I/O-Bound")) {
                int cyclesEx = (Integer) Priory.getValue();
                int cyclesIO = (Integer) CyclesIO.getValue();
                
            newProcess = new Process(
                nombre, 
                ProcessType.IO_BOUND,
                cyclesEx, 
                cyclesIO, 
                instrucciones, 
                priory
            ); 
        }else { // Es "CPU-Bound"
            
            newProcess = new Process(
                nombre, 
                ProcessType.CPU_BOUND,
                instrucciones, 
                priory 
            );
        }
        if (this.os != null) {
            this.os.addProcess(newProcess);
            // Mensaje de Proceso creado correctamente 
            JOptionPane.showMessageDialog(this, "El " + nombre + " creado exitosamente.");
        
        /** Limpiar los campos 
        NombreProceso.setText("");
        CantidadInstrucciones.setValue(0);
        Priory.setValue(0);
        Priory.setValue(0);
        CyclesIO.setValue(0);
        */
        }else {
            JOptionPane.showMessageDialog(this, "Error: El Sistema Operativo no está inicializado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        } catch (NumberFormatException e) {
            
        // Captura error de Formato 
        JOptionPane.showMessageDialog(this, 
            "Error: Revisa los campos numéricos.\nDeben ser números válidos.", 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);
        
        } catch (Exception e) {
            // Capturar cualquier otro error 
             JOptionPane.showMessageDialog(this, 
                "Ocurrió un error: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IniciarProcesoActionPerformed

    private void cargarFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFileActionPerformed
        JFileChooser selarchivo = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(" Archivos JSON", "json");
        selarchivo.setFileFilter(filter);
        int val = selarchivo.showOpenDialog(null);
        if (val == JFileChooser.APPROVE_OPTION){
            if(selarchivo.getSelectedFile() != null){
            selectedFile = selarchivo.getSelectedFile();
            JOptionPane.showMessageDialog(null, "El archivo seleccionado es: " + selectedFile.getName());}
        else {
            JOptionPane.showMessageDialog(null,"Archivo no seleccionado");
        }}
    }//GEN-LAST:event_cargarFileActionPerformed

    private void GuardarPlanificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPlanificacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarPlanificacionMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bloqueados;
    private javax.swing.JSpinner CantidadInstrucciones;
    private javax.swing.JSpinner CyclesEx;
    private javax.swing.JSpinner CyclesIO;
    private javax.swing.JLabel Finalizados;
    private javax.swing.JButton GuardarPlanificacion;
    private javax.swing.JButton IniciarProceso;
    private javax.swing.JLabel Listo;
    private javax.swing.JLabel Listo1;
    private javax.swing.JTextField NombreProceso;
    private javax.swing.JComboBox<String> PoliticaName;
    private javax.swing.JSpinner Priory;
    private javax.swing.JSpinner Spinnerciclo;
    private javax.swing.JComboBox<String> TypeProcess;
    private javax.swing.JButton cargarDatos;
    private javax.swing.JButton cargarFile;
    private javax.swing.JLabel ciclo;
    private javax.swing.JLabel ciclo1;
    private javax.swing.JLabel ciclo2;
    private javax.swing.JLabel ciclo3;
    private javax.swing.JTable colaBloqueado;
    private javax.swing.JTable colaListos;
    private javax.swing.JTable colaOut;
    private javax.swing.JTable colaSupendidos;
    private javax.swing.JLabel instrucciones;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel quantum;
    private javax.swing.JButton randomProcess;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
