/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import javax.swing.JLabel;

/**
 *
 * @author rtkn0_z8ls
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quantumchoice = new java.awt.Choice();
        titulo = new javax.swing.JLabel();
        politicachoice = new java.awt.Choice();
        label1 = new javax.swing.JLabel();
        instrucciones = new javax.swing.JLabel();
        spinnerinstrucciones = new javax.swing.JSpinner();
        boxtipo = new javax.swing.JComboBox<>();
        tipo = new javax.swing.JLabel();
        ciclo = new javax.swing.JLabel();
        Spinnerciclo = new javax.swing.JSpinner();
        quantum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        boxtipo1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        Listalisto = new java.awt.Panel();
        Listabloqueados = new java.awt.Panel();
        ListaFinalizado = new java.awt.Panel();
        Listalisto1 = new java.awt.Panel();
        Listo = new javax.swing.JLabel();
        Bloqueados = new javax.swing.JLabel();
        Finalizados = new javax.swing.JLabel();
        Listo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        jPanel3.setBackground(new java.awt.Color(245, 247, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(156, 209, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre del Proceso");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Quantum");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));
        jPanel2.add(quantumchoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 160, -1));

        titulo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Simulador de Procesos ");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        jPanel2.add(politicachoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 380, -1));

        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 102, 102));
        label1.setText("Introduzca los atributos del proceso  ");
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        instrucciones.setBackground(new java.awt.Color(0, 0, 0));
        instrucciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        instrucciones.setForeground(new java.awt.Color(0, 0, 0));
        instrucciones.setText("N. de Instrucciones:");
        jPanel2.add(instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        spinnerinstrucciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        spinnerinstrucciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(spinnerinstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, 25));

        boxtipo.setBackground(new java.awt.Color(51, 51, 51));
        boxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxtipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtipoActionPerformed(evt);
            }
        });
        jPanel2.add(boxtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 190, 25));

        tipo.setBackground(new java.awt.Color(0, 0, 0));
        tipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipo.setForeground(new java.awt.Color(0, 0, 0));
        tipo.setText("Tipo:");
        jPanel2.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        ciclo.setBackground(new java.awt.Color(0, 0, 0));
        ciclo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo.setForeground(new java.awt.Color(0, 0, 0));
        ciclo.setText("Ciclo (ms): ");
        jPanel2.add(ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        Spinnerciclo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        Spinnerciclo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Spinnerciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 75, 25));

        quantum.setBackground(new java.awt.Color(0, 0, 0));
        quantum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quantum.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(quantum, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 179, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Politica");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Nombre");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 540, -1));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cargar JSON/CSV");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 120, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reiniciar Proceso");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 120, 30));

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Cargar Datos");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 120, 30));

        jButton4.setBackground(new java.awt.Color(102, 153, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Iniciar Proceso");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 120, 30));

        boxtipo1.setBackground(new java.awt.Color(255, 255, 255));
        boxtipo1.setEditable(true);
        boxtipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxtipo1.setBorder(null);
        boxtipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtipo1ActionPerformed(evt);
            }
        });
        jPanel2.add(boxtipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 190, 25));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 280));

        jPanel4.setBackground(new java.awt.Color(179, 220, 249));
        jPanel4.setFocusTraversalPolicyProvider(true);

        Listalisto.setBackground(new java.awt.Color(236, 250, 245));
        Listalisto.setPreferredSize(new java.awt.Dimension(210, 244));

        javax.swing.GroupLayout ListalistoLayout = new javax.swing.GroupLayout(Listalisto);
        Listalisto.setLayout(ListalistoLayout);
        ListalistoLayout.setHorizontalGroup(
            ListalistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        ListalistoLayout.setVerticalGroup(
            ListalistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        Listabloqueados.setBackground(new java.awt.Color(236, 250, 245));
        Listabloqueados.setPreferredSize(new java.awt.Dimension(210, 244));

        javax.swing.GroupLayout ListabloqueadosLayout = new javax.swing.GroupLayout(Listabloqueados);
        Listabloqueados.setLayout(ListabloqueadosLayout);
        ListabloqueadosLayout.setHorizontalGroup(
            ListabloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        ListabloqueadosLayout.setVerticalGroup(
            ListabloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        ListaFinalizado.setBackground(new java.awt.Color(236, 250, 245));
        ListaFinalizado.setPreferredSize(new java.awt.Dimension(210, 0));

        javax.swing.GroupLayout ListaFinalizadoLayout = new javax.swing.GroupLayout(ListaFinalizado);
        ListaFinalizado.setLayout(ListaFinalizadoLayout);
        ListaFinalizadoLayout.setHorizontalGroup(
            ListaFinalizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        ListaFinalizadoLayout.setVerticalGroup(
            ListaFinalizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Listalisto1.setBackground(new java.awt.Color(236, 250, 245));
        Listalisto1.setPreferredSize(new java.awt.Dimension(210, 244));

        javax.swing.GroupLayout Listalisto1Layout = new javax.swing.GroupLayout(Listalisto1);
        Listalisto1.setLayout(Listalisto1Layout);
        Listalisto1Layout.setHorizontalGroup(
            Listalisto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        Listalisto1Layout.setVerticalGroup(
            Listalisto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        Listo.setForeground(new java.awt.Color(102, 102, 102));
        Listo.setText("Listos");

        Bloqueados.setForeground(new java.awt.Color(102, 102, 102));
        Bloqueados.setText("Bloqueados");

        Finalizados.setForeground(new java.awt.Color(102, 102, 102));
        Finalizados.setText("Finalizados");

        Listo1.setForeground(new java.awt.Color(102, 102, 102));
        Listo1.setText("Suspendidos");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Proceso en Ejecución");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Listalisto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Listo1)
                                .addGap(102, 102, 102)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Listalisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Listo)
                                .addGap(90, 90, 90)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(Listabloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(Bloqueados)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(ListaFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Finalizados)
                                .addGap(87, 87, 87)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Listo1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Listalisto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Listo)
                            .addComponent(Bloqueados)
                            .addComponent(Finalizados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ListaFinalizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Listabloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Listalisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 1120, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxtipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void boxtipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxtipo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bloqueados;
    private javax.swing.JLabel Finalizados;
    private java.awt.Panel ListaFinalizado;
    private java.awt.Panel Listabloqueados;
    private java.awt.Panel Listalisto;
    private java.awt.Panel Listalisto1;
    private javax.swing.JLabel Listo;
    private javax.swing.JLabel Listo1;
    private javax.swing.JSpinner Spinnerciclo;
    private javax.swing.JComboBox<String> boxtipo;
    private javax.swing.JComboBox<String> boxtipo1;
    private javax.swing.JLabel ciclo;
    private javax.swing.JLabel instrucciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label1;
    private java.awt.Choice politicachoice;
    private javax.swing.JLabel quantum;
    private java.awt.Choice quantumchoice;
    private javax.swing.JSpinner spinnerinstrucciones;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
