/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;
import requirements.OS;
import requirements.Process;
import structures.ProcessType;
import javax.swing.JOptionPane;
import SchedulerTechniques.StrategyScheduler;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import requirements.PCB;
import requirements.Process;
import requirements.SimulationListener;
import structures.ProcessType;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/**
 *
 * @author rtkn0_z8ls
 */
public class PanelPrincipal extends javax.swing.JFrame implements SimulationListener {
    private File selectedFile;
    private OS os; // Referenciamos a nuestro OS
    
    private DefaultListModel<String> modeloListaListos = new DefaultListModel<>();
    private DefaultListModel<String> modeloListaBloqueados = new DefaultListModel<>();
    private DefaultListModel<String> modeloListaTerminados = new DefaultListModel<>();
    private DefaultListModel<String> modeloListaSupendido = new DefaultListModel<>();
    private DefaultListModel<String> modeloBloqueadoSupendido = new DefaultListModel<>();
    
    // Para Grafico de CPU
    private XYSeries utilizationSeries;
    private ChartPanel chartPanel;
    private JFreeChart utilizationChart;
   
    // Pata Grafico de Procesos 
    private DefaultPieDataset processTypeDataset;
    private JFreeChart processTypeChart;
    private ChartPanel processTypeChartPanel; 

    // Contadores
    private int cpuBoundCount = 0;
    private int ioBoundCount = 0;

    
    public PanelPrincipal(OS os) { 
        initComponents();
        this.os = os;
        this.setVisible(true);
        
        // Para Grafico de CPU
        utilizationSeries = new XYSeries("Utilidad de CPU");
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(utilizationSeries);utilizationChart = ChartFactory.createXYLineChart(
            "Utilidad de CPU vs. Tiempo", // Título del Gráfico
            "Ciclos de Tiempo",           // Título del Eje X
            "Utilidad (%)",               // Título del Eje Y
            dataset
        );
        chartPanel = new ChartPanel(utilizationChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 300));
        
            colaListos.setModel(modeloListaListos);
            colaBloqueados.setModel(modeloListaBloqueados);
            colaFinalizados.setModel(modeloListaTerminados);
            colaSuspendidosB.setModel(modeloBloqueadoSupendido);
            colaSuspendidosL.setModel(modeloListaSupendido);

         processTypeDataset = new DefaultPieDataset();
        
        processTypeDataset.setValue("CPU-Bound", 0.0); 
        processTypeDataset.setValue("I/O-Bound", 0.0);

        processTypeChart = ChartFactory.createPieChart(
            "Composición de Procesos Cargados", // Título
            processTypeDataset,             // Datos
            true,                           // Incluir leyenda
            true,                           // Incluir tooltips
            false                           // Incluir URLs
        );
    
    // Crear el panel de la gráfica
    processTypeChartPanel = new ChartPanel(processTypeChart);
    processTypeChartPanel.setPreferredSize(new java.awt.Dimension(350, 300));
        
        this.os.addSimulationListener(this);
        
     // 1. Poblar el JComboBox de Politicas de Planificacion
        String[] Politicas = { 
        "Round Robin", 
        "FCFS", 
        "SJF", 
        "SRT", 
        "HRRN", 
        "FB" 
        };
        PoliticaName.setModel(new javax.swing.DefaultComboBoxModel<>(Politicas));
        
         // 2. Poblar el JComboBox de Tipos de Proceso
        String[] TipoProceso = { 
            "CPU-Bound", 
            "I/O-Bound"
        };
        TypeProcess.setModel(new javax.swing.DefaultComboBoxModel<>(TipoProceso));
    }
        

        
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        instrucciones = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        ciclo = new javax.swing.JLabel();
        Spinnerciclo = new javax.swing.JSpinner();
        quantum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreProceso = new javax.swing.JTextField();
        randomProcess = new javax.swing.JButton();
        GuardarPlanificacion = new javax.swing.JButton();
        CantidadInstrucciones = new javax.swing.JSpinner();
        PoliticaName = new javax.swing.JComboBox<>();
        TypeProcess = new javax.swing.JComboBox<>();
        ciclo1 = new javax.swing.JLabel();
        ciclo2 = new javax.swing.JLabel();
        ciclo3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CyclesIO = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        IniciarProceso = new javax.swing.JButton();
        cargarFile = new javax.swing.JButton();
        CyclesEx = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Listo = new javax.swing.JLabel();
        Bloqueados = new javax.swing.JLabel();
        Finalizados = new javax.swing.JLabel();
        Listo1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        colaFinalizados = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        colaSuspendidosB = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        colaSuspendidosL = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        colaBloqueados = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        colaListos = new javax.swing.JList<>();
        Listo2 = new javax.swing.JLabel();
        Listo3 = new javax.swing.JLabel();
        MostrarGrafica = new javax.swing.JButton();
        MostrarGrafica2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        jPanel3.setBackground(new java.awt.Color(245, 247, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(156, 209, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Proceso");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        titulo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        titulo.setText("Simulador de Procesos ");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        instrucciones.setBackground(new java.awt.Color(0, 0, 0));
        instrucciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        instrucciones.setText("N. de Instrucciones:");
        jPanel2.add(instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        tipo.setBackground(new java.awt.Color(0, 0, 0));
        tipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipo.setText("Tipo:");
        jPanel2.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        ciclo.setBackground(new java.awt.Color(0, 0, 0));
        ciclo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo.setText("generar excepcion");
        jPanel2.add(ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 120, -1));

        Spinnerciclo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        Spinnerciclo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Spinnerciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 170, 25));

        quantum.setBackground(new java.awt.Color(0, 0, 0));
        quantum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.add(quantum, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 179, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Duracion del ciclo Ejec.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        NombreProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProcesoActionPerformed(evt);
            }
        });
        jPanel2.add(NombreProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, -1));

        randomProcess.setBackground(new java.awt.Color(0, 102, 255));
        randomProcess.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        randomProcess.setForeground(new java.awt.Color(255, 255, 255));
        randomProcess.setText("Cargar Aleatorios");
        randomProcess.setBorder(null);
        randomProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomProcessActionPerformed(evt);
            }
        });
        jPanel2.add(randomProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 120, 30));

        GuardarPlanificacion.setBackground(new java.awt.Color(0, 102, 255));
        GuardarPlanificacion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        GuardarPlanificacion.setForeground(new java.awt.Color(255, 255, 255));
        GuardarPlanificacion.setText("Guardar");
        GuardarPlanificacion.setBorder(null);
        GuardarPlanificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarPlanificacionMouseClicked(evt);
            }
        });
        GuardarPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPlanificacionActionPerformed(evt);
            }
        });
        jPanel2.add(GuardarPlanificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 100, 30));

        CantidadInstrucciones.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10000, 1));
        CantidadInstrucciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CantidadInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 25));

        PoliticaName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PoliticaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoliticaNameActionPerformed(evt);
            }
        });
        jPanel2.add(PoliticaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 170, -1));

        TypeProcess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TypeProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeProcessActionPerformed(evt);
            }
        });
        jPanel2.add(TypeProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));

        ciclo1.setBackground(new java.awt.Color(0, 0, 0));
        ciclo1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo1.setText("satisfacer excepcion");
        jPanel2.add(ciclo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, -1));

        ciclo2.setBackground(new java.awt.Color(0, 0, 0));
        ciclo2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo2.setText("Cantidad de ciclos para ");
        jPanel2.add(ciclo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, -1));

        ciclo3.setBackground(new java.awt.Color(0, 0, 0));
        ciclo3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo3.setText("Cantidad de ciclos para ");
        jPanel2.add(ciclo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 160, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Politica");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        CyclesIO.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        CyclesIO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CyclesIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 170, 25));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 700, -1));

        IniciarProceso.setBackground(new java.awt.Color(102, 153, 255));
        IniciarProceso.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        IniciarProceso.setForeground(new java.awt.Color(255, 255, 255));
        IniciarProceso.setText("Iniciar Proceso");
        IniciarProceso.setBorder(null);
        IniciarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarProcesoActionPerformed(evt);
            }
        });
        jPanel2.add(IniciarProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 100, 30));

        cargarFile.setBackground(new java.awt.Color(0, 102, 255));
        cargarFile.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cargarFile.setForeground(new java.awt.Color(255, 255, 255));
        cargarFile.setText("Subir CSV");
        cargarFile.setBorder(null);
        cargarFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFileActionPerformed(evt);
            }
        });
        jPanel2.add(cargarFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 120, 30));

        CyclesEx.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        CyclesEx.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CyclesEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 170, 25));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 280));

        jPanel4.setBackground(new java.awt.Color(179, 220, 249));
        jPanel4.setFocusTraversalPolicyProvider(true);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Listo.setForeground(new java.awt.Color(102, 102, 102));
        Listo.setText("Listos");
        jPanel4.add(Listo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        Bloqueados.setForeground(new java.awt.Color(102, 102, 102));
        Bloqueados.setText("Bloqueados");
        jPanel4.add(Bloqueados, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 20));

        Finalizados.setForeground(new java.awt.Color(102, 102, 102));
        Finalizados.setText("Finalizados");
        jPanel4.add(Finalizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        Listo1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        Listo1.setForeground(new java.awt.Color(102, 102, 102));
        Listo1.setText("Procesos en Ejecucion ");
        jPanel4.add(Listo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        colaFinalizados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(colaFinalizados);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 220, 240));

        colaSuspendidosB.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(colaSuspendidosB);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 220, 130));

        colaSuspendidosL.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(colaSuspendidosL);

        jPanel4.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 220, 180));

        colaBloqueados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(colaBloqueados);

        jPanel4.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 220, 240));

        colaListos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(colaListos);

        jPanel4.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 240));

        Listo2.setForeground(new java.awt.Color(102, 102, 102));
        Listo2.setText("Suspendidos Bloqueados");
        jPanel4.add(Listo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, -1));

        Listo3.setForeground(new java.awt.Color(102, 102, 102));
        Listo3.setText("Suspendidos Listos");
        jPanel4.add(Listo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        MostrarGrafica.setText("Mostrar Grafica");
        MostrarGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGraficaActionPerformed(evt);
            }
        });
        jPanel4.add(MostrarGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 220, -1));

        MostrarGrafica2.setText("Mostrar Grafica");
        MostrarGrafica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGrafica2ActionPerformed(evt);
            }
        });
        jPanel4.add(MostrarGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Uso de la CPU");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 90, 20));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Procesos Cargados");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 1120, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este método es llamado por el HILO DEL OS (el "Ingeniero")
     * cada vez que el OS llama a fireQueuesChanged().
     */
    @Override
    public void onProcessQueuesChanged() {
        
        // ¡NO podemos actualizar la GUI directamente desde aquí!
        // (Estamos en el hilo incorrecto).

        // 1. Creamos una "tarea" (un objeto Runnable) para el hilo de la GUI.
        Runnable tareaDeActualizacion = new Runnable() {
            @Override
            public void run() {
                
                actualizarTodasLasTablas(); 
                updateUtilizationChart();
            }
        };

        // 2. Le entregamos la "tarea" a Swing (el "buzón") para que la ponga 
        // en la cola de tareas del "Pintor" (el hilo de la GUI).
        SwingUtilities.invokeLater(tareaDeActualizacion);
        
        
    } 
    
    /**
        * MÉTODO "JEFE" (Casi igual, solo cambian los nombres de los modelos)
        */
       private void actualizarTodasLasTablas() {

           // 1. Actualiza la lista de LISTOS
           actualizarListaUnica(
                   os.getReadyQueueSnapshot(),  // La "foto" segura de la cola
                   modeloListaListos            // El modelo de la JList
           );
       
           // 2. Actualiza la lista de BLOQUEADOS
           actualizarListaUnica(
                   os.getBlockedQueueSnapshot(),
                   modeloListaBloqueados
           );

           // 3. Actualiza la lista de TERMINADOS
           actualizarListaUnica(
                   os.getFinishedListSnapshot(),
                   modeloListaTerminados
           );

           // Añade los Ready-Suspended
           actualizarListaUnica(
                os.getReadySuspendedQueueSnapshot(), 
                modeloListaSupendido              
            );
           actualizarListaUnica(
                os.getBlockedSuspendedQueueSnapshot(), 
                modeloBloqueadoSupendido              
            );
           
           
           }
    
    public void updateProcessTypeChart() {
    // 1. Obtener el conteo del OS
    int[] counts = os.countProcessTypes(); 
    int cpuBoundCount = counts[0];
    int ioBoundCount = counts[1];
    int totalCount = cpuBoundCount + ioBoundCount;

        // 3. Calcular porcentajes y actualizar el dataset
       processTypeDataset.setValue("CPU-Bound", cpuBoundCount);
       processTypeDataset.setValue("I/O-Bound", ioBoundCount);
       org.jfree.chart.plot.PiePlot plot = (org.jfree.chart.plot.PiePlot) processTypeChart.getPlot();
       
       plot.setLegendLabelGenerator(new org.jfree.chart.labels.StandardPieSectionLabelGenerator(
        "{0} ({1} | {2})", 
        new java.text.DecimalFormat("0"), // Formato para el conteo
        new java.text.DecimalFormat("0.0%") // Formato para el porcentaje
    ));

    // 4. Actualizar el título
    processTypeChart.setTitle("Composición de Procesos Cargados (Total: " + totalCount + ")");
    }   
    /**
    * 
    *
    * @param procesos La "foto" (List<Process>) de la cola a dibujar.
    * @param modelo El DefaultListModel<String> de la JList que se va a actualizar.
    */
        private void actualizarListaUnica(java.util.List<Process> procesos, DefaultListModel<String> modelo) {
            actualizarListaUnica(procesos, modelo, true);
        }

        /**
         * Sobrecarga del método AYUDANTE que permite decidir si se limpia la lista o no.
         *
         * @param procesos La "foto" (List<Process>) de la cola a dibujar.
         * @param modelo El DefaultListModel<String> de la JList que se va a actualizar.
         * @param limpiarLista Si es true, limpia la lista (modelo.clear()) antes de añadir.
         */
        private void actualizarListaUnica(java.util.List<Process> procesos, DefaultListModel<String> modelo, boolean limpiarLista) {

            // 1. Limpia la lista si se le indica
            if (limpiarLista) {
                modelo.clear(); // El comando para limpiar un JList
            }

            // 2. Itera sobre la "foto" (la List<Process> segura)
            for (Process p : procesos) {
                PCB pcb = p.getPCB();

                
                // Creamos un ÚNICO String con la info que queremos mostrar.
                // Puedes poner lo que quieras aquí.
                String textoProceso = String.format("Nombre: %s | PC: %d | MAR: %d", 
                                  pcb.getName(), 
                                  pcb.getPc(),
                                  pcb.getMar());

                // 4. Añade el String al modelo
                modelo.addElement(textoProceso);
            }
        }
    private void updateUtilizationChart() {
        // Es vital usar SwingUtilities.invokeLater para asegurar que las actualizaciones
        // de la GUI se hagan en el hilo correcto
       
            java.util.List<Double> history = os.getUtilizationHistory();

            // Limpiamos y reconstruimos la serie para evitar duplicados y errores de concurrencia
            utilizationSeries.clear();
            for (int i = 0; i < history.size(); i++) {
                // El Eje X es el ciclo (i + 1), el Eje Y es el valor de utilidad
                utilizationSeries.add(i + 1, history.get(i)); 
            }
    }

    private void randomProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomProcessActionPerformed
        Random rand = new Random();

        // 2. Definimos los rangos para nuestros valores aleatorios
        int minInstrucciones = 20;
        int maxInstrucciones = 100;

        int minRafagaCPU = 5;  // Ráfaga de CPU antes de E/S
        int maxRafagaCPU = 15;

        int minTiempoIO = 10;  // Tiempo que tarda la E/S
        int maxTiempoIO = 30;
        
        System.out.println("--- Iniciando carga masiva de 20 procesos aleatorios ---");

        // 3. El bucle para crear 20 procesos
        for (int i = 0; i < 20; i++) {
            String nombre = "Proceso-" + (i + 1);
            int prioridadPorDefecto = 1;
            ProcessType tipo = rand.nextBoolean() ? ProcessType.CPU_BOUND : ProcessType.IO_BOUND;
            int instrucciones = rand.nextInt(maxInstrucciones - minInstrucciones + 1) + minInstrucciones;
            Process p;
            if (tipo == ProcessType.CPU_BOUND) {
            p = new Process(
                nombre,
                tipo,
                instrucciones,
                prioridadPorDefecto
            ); 
            System.out.println("Proceso (CPU-Bound) generado: " + nombre + " [Inst: " + instrucciones + "]");
           } else{
                int rafagaCPU = rand.nextInt(maxRafagaCPU - minRafagaCPU + 1) + minRafagaCPU;
                int tiempoBloqueo = rand.nextInt(maxTiempoIO - minTiempoIO + 1) + minTiempoIO;
                p = new Process(
                nombre,
                tipo,
                rafagaCPU,       // cyclesExcepcion
                tiempoBloqueo,   // cyclesCompleteIO
                instrucciones,
                prioridadPorDefecto
            );
            System.out.println("Proceso (I/O-Bound) generado: " + nombre + " [Inst: " + instrucciones + ", RafagaCPU: " + rafagaCPU + ", T. E/S: " + tiempoBloqueo + "]");
            }
           this.os.addProcess(p);
        }
        JOptionPane.showMessageDialog(this, "Se han cargado 20 procesos aleatorios.");
    }//GEN-LAST:event_randomProcessActionPerformed
    private boolean isEmpty(){
        return selectedFile  == null;
    }
    
    private void GuardarPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPlanificacionActionPerformed
        String politicaSeleccionada = (String) PoliticaName.getSelectedItem();
        StrategyScheduler estrategia;
        
        switch (politicaSeleccionada) {
            case "FCFS":
                estrategia = StrategyScheduler.FirstComeFirstServe;
                break;
            case "Round Robin":
                estrategia = StrategyScheduler.RoundRobin;
                break;
            case "SJF":
                estrategia = StrategyScheduler.SJF;
                break;
            case "SRT":
                estrategia = StrategyScheduler.SRT;
                break;
            case "HRRN":
                estrategia = StrategyScheduler.HRRN;
                break;
            case "FB":
                estrategia = StrategyScheduler.FB;
                break;
            default:
                System.out.println("Política desconocida, usando FCFS por defecto.");
                estrategia = StrategyScheduler.RoundRobin; // Valor por defecto
            }
        if (this.os != null) {
        // Accedemos al scheduler a través del OS y cambiamos la estrategia
        this.os.setSchedulingStrategy(estrategia);
        System.out.println("Estrategia de planificación cambiada a: " + politicaSeleccionada);
    }
    }//GEN-LAST:event_GuardarPlanificacionActionPerformed

    private void NombreProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProcesoActionPerformed

    private void PoliticaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoliticaNameActionPerformed
      
    }//GEN-LAST:event_PoliticaNameActionPerformed

    private void TypeProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeProcessActionPerformed
     
    }//GEN-LAST:event_TypeProcessActionPerformed

    private void IniciarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarProcesoActionPerformed
        try {
        // 1. LEER DATOS EN COMUN
        String nombre = NombreProceso.getText();
        int instrucciones = (Integer) CantidadInstrucciones.getValue();
        int priory = 1; //-> Por defecto
        
        // 2. LEER TIPO DE PROCESO SELECCIONADO
        String TypeSelected = (String) TypeProcess.getSelectedItem();
        
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para el proceso.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Process newProcess; // El proceso que vamos a crear
        
            // 3. DECIDIR QUÉ CONSTRUCTOR USAR
            if (TypeSelected.equals("I/O-Bound")) {
                int cyclesEx = (Integer) CyclesEx.getValue();
                int cyclesIO = (Integer) CyclesIO.getValue();
                
            newProcess = new Process(
                nombre, 
                ProcessType.IO_BOUND,
                cyclesEx, 
                cyclesIO, 
                instrucciones, 
                priory
            ); 
        }else { // Es "CPU-Bound"
            
            newProcess = new Process(
                nombre, 
                ProcessType.CPU_BOUND,
                instrucciones, 
                priory 
            );
        }
        if (this.os != null) {
            this.os.addProcess(newProcess);
            // Mensaje de Proceso creado correctamente 
            JOptionPane.showMessageDialog(this, "El " + nombre + " creado exitosamente.");
        
        /** Limpiar los campos 
        NombreProceso.setText("");
        CantidadInstrucciones.setValue(0);
        Priory.setValue(0);
        Priory.setValue(0);
        CyclesIO.setValue(0);
        */
        }else {
            JOptionPane.showMessageDialog(this, "Error: El Sistema Operativo no está inicializado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        } catch (NumberFormatException e) {
            
        // Captura error de Formato 
        JOptionPane.showMessageDialog(this, 
            "Error: Revisa los campos numéricos.\nDeben ser números válidos.", 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);
        
        } catch (Exception e) {
            // Capturar cualquier otro error 
             JOptionPane.showMessageDialog(this, 
                "Ocurrió un error: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IniciarProcesoActionPerformed

    private void cargarFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFileActionPerformed
        JFileChooser selarchivo = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(" Archivos CSV", "csv");
        selarchivo.setFileFilter(filter);
        
        int val = selarchivo.showOpenDialog(null);
       if (val == JFileChooser.APPROVE_OPTION){
        File file = selarchivo.getSelectedFile();
        if(file != null){
            this.selectedFile = file;
            JOptionPane.showMessageDialog(null, "Iniciando carga de procesos desde: " + file.getName());
            
            // 2. Lógica de lectura de CSV
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                boolean isFirstLine = true;
                
                // Procesar línea por línea
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) continue; // Ignorar líneas vacías
                    
                    // Lógica simple para intentar omitir una línea de cabecera
                    if (isFirstLine) {
                        if (line.trim().toLowerCase().startsWith("nombre") || line.trim().toLowerCase().startsWith("name")) {
                            isFirstLine = false;
                            continue; // Saltar la línea de cabecera
                        }
                        isFirstLine = false;
                    }
                    
                    // 3. Llamar al método de parsing e inyección de procesos
                    createProcessFromCSVLine(line);
                }

                JOptionPane.showMessageDialog(null, "Procesos cargados exitosamente.");
                // Notificar al OS/GUI para que se refresquen las listas
                this.os.fireQueuesChanged(); 

                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error al leer el archivo CSV: " + e.getMessage(), "Error de Archivo", JOptionPane.ERROR_MESSAGE);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Error de formato. Asegúrese de que los campos numéricos (Instrucciones, Prioridad, Ciclos) sean válidos. Error: " + e.getMessage(), "Error de Datos", JOptionPane.ERROR_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al procesar la línea del archivo. Revise el formato. Error: " + e.getMessage(), "Error de Formato", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null,"Archivo no seleccionado");
            }
        }
    }//GEN-LAST:event_cargarFileActionPerformed

    private void createProcessFromCSVLine(String line) throws NumberFormatException, Exception {
            // Se espera el formato CSV con coma (,) como delimitador:
            // Nombre,Tipo,Instrucciones,Prioridad,CiclosExcepcion,CyclesCompleteIO

            String[] data = line.split(",");

            // Se requieren al menos 4 campos (Nombre, Tipo, Instrucciones, Prioridad)
            if (data.length < 4) {
                System.err.println("Línea ignorada: datos insuficientes -> " + line);
                return; 
            }

            String name = data[0].trim();
            String typeStr = data[1].trim().toUpperCase();
            // Parsea los campos numéricos
            int instructions = Integer.parseInt(data[2].trim());
            int priory = Integer.parseInt(data[3].trim());

            requirements.Process newProcess;

            if (typeStr.contains("CPU")) {
                // Constructor CPU-Bound: (name, processType, instructions, priory)
                newProcess = new requirements.Process(
                    name, 
                    structures.ProcessType.CPU_BOUND, 
                    instructions, 
                    priory
                );
                this.os.addProcess(newProcess);

            } else if (typeStr.contains("I/O")) {
                // Para I/O-Bound se requieren 6 campos
                if (data.length < 6) {
                     throw new Exception("Línea I/O-Bound incompleta. Se requieren 6 campos: " + line);
                }

                int cyclesExcepcion = Integer.parseInt(data[4].trim());
                int cyclesCompleteIO = Integer.parseInt(data[5].trim());

                // Constructor I/O-Bound: (name, processType, cyclesExcepcion, cyclesCompleteIO, instructions, priory)
                newProcess = new requirements.Process(
                    name, 
                    structures.ProcessType.IO_BOUND, 
                    cyclesExcepcion, 
                    cyclesCompleteIO, 
                    instructions, 
                    priory
                );
                this.os.addProcess(newProcess); // Agrega el proceso al OS

            } else {
                System.err.println("Tipo de proceso desconocido. Línea ignorada: " + line);
    }
}
    private void GuardarPlanificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPlanificacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarPlanificacionMouseClicked

    private void MostrarGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGraficaActionPerformed
        javax.swing.JFrame frameGrafica = new javax.swing.JFrame("Utilidad de CPU");
        frameGrafica.getContentPane().add(chartPanel, java.awt.BorderLayout.CENTER);
        frameGrafica.pack();
        frameGrafica.setSize(600, 400); // Tamaño inicial
        frameGrafica.setVisible(true);

    }//GEN-LAST:event_MostrarGraficaActionPerformed

    private void MostrarGrafica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGrafica2ActionPerformed
       updateProcessTypeChart(); 
    
        if (processTypeChartPanel.getParent() != null) {
            processTypeChartPanel.getParent().remove(processTypeChartPanel);
        }

        javax.swing.JFrame frameComposicion = new javax.swing.JFrame("Composición de Procesos");
        frameComposicion.getContentPane().setLayout(new java.awt.BorderLayout());
        frameComposicion.getContentPane().add(processTypeChartPanel, java.awt.BorderLayout.CENTER);

        frameComposicion.pack();
        frameComposicion.setSize(500, 400); 
        frameComposicion.setVisible(true);
    }//GEN-LAST:event_MostrarGrafica2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bloqueados;
    private javax.swing.JSpinner CantidadInstrucciones;
    private javax.swing.JSpinner CyclesEx;
    private javax.swing.JSpinner CyclesIO;
    private javax.swing.JLabel Finalizados;
    private javax.swing.JButton GuardarPlanificacion;
    private javax.swing.JButton IniciarProceso;
    private javax.swing.JLabel Listo;
    private javax.swing.JLabel Listo1;
    private javax.swing.JLabel Listo2;
    private javax.swing.JLabel Listo3;
    private javax.swing.JButton MostrarGrafica;
    private javax.swing.JButton MostrarGrafica2;
    private javax.swing.JTextField NombreProceso;
    private javax.swing.JComboBox<String> PoliticaName;
    private javax.swing.JSpinner Spinnerciclo;
    private javax.swing.JComboBox<String> TypeProcess;
    private javax.swing.JButton cargarFile;
    private javax.swing.JLabel ciclo;
    private javax.swing.JLabel ciclo1;
    private javax.swing.JLabel ciclo2;
    private javax.swing.JLabel ciclo3;
    private javax.swing.JList<String> colaBloqueados;
    private javax.swing.JList<String> colaFinalizados;
    private javax.swing.JList<String> colaListos;
    private javax.swing.JList<String> colaSuspendidosB;
    private javax.swing.JList<String> colaSuspendidosL;
    private javax.swing.JLabel instrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel quantum;
    private javax.swing.JButton randomProcess;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
