/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import SchedulerTechniques.StrategyScheduler;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import requirements.Process;

import requirements.Scheduler;
import structures.ProcessType;


/**
 *
 * @author rtkn0_z8ls
 */
public class PanelPrincipal extends javax.swing.JFrame {
    private File selectedFile;
    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() { 
        this.setVisible(true);
        initComponents();
     // 1. Poblar el JComboBox de Politicas de Planificacion
        String[] Politicas = { 
        "Round Robin", 
        "FCFS", 
        "SJF", 
        "SRT", 
        "HRRN", 
        "FB" 
        };
        PoliticaName.setModel(new javax.swing.DefaultComboBoxModel<>(Politicas));
        
         // 2. Poblar el JComboBox de Tipos de Proceso
        String[] TipoProceso = { 
            "CPU-Bound", 
            "I/O-Bound"
        };
        TypeProcess.setModel(new javax.swing.DefaultComboBoxModel<>(TipoProceso));

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        instrucciones = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        ciclo = new javax.swing.JLabel();
        Spinnerciclo = new javax.swing.JSpinner();
        quantum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreProceso = new javax.swing.JTextField();
        randomProcess = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cargarDatos = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        CantidadInstrucciones = new javax.swing.JSpinner();
        PoliticaName = new javax.swing.JComboBox<>();
        TypeProcess = new javax.swing.JComboBox<>();
        ciclo1 = new javax.swing.JLabel();
        ciclo2 = new javax.swing.JLabel();
        ciclo3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CyclesIO = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        IniciarProceso = new javax.swing.JButton();
        Priory = new javax.swing.JSpinner();
        cargarFile = new javax.swing.JButton();
        CyclesEx = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Listalisto = new java.awt.Panel();
        Listabloqueados = new java.awt.Panel();
        ListaFinalizado = new java.awt.Panel();
        Listalisto1 = new java.awt.Panel();
        Listo = new javax.swing.JLabel();
        Bloqueados = new javax.swing.JLabel();
        Finalizados = new javax.swing.JLabel();
        Listo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        jPanel3.setBackground(new java.awt.Color(245, 247, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(156, 209, 247));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Proceso");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        titulo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        titulo.setText("Simulador de Procesos ");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        instrucciones.setBackground(new java.awt.Color(0, 0, 0));
        instrucciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        instrucciones.setText("N. de Instrucciones:");
        jPanel2.add(instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        tipo.setBackground(new java.awt.Color(0, 0, 0));
        tipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipo.setText("Tipo:");
        jPanel2.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        ciclo.setBackground(new java.awt.Color(0, 0, 0));
        ciclo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo.setText("generar excepcion");
        jPanel2.add(ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 120, -1));

        Spinnerciclo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        Spinnerciclo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Spinnerciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 170, 25));

        quantum.setBackground(new java.awt.Color(0, 0, 0));
        quantum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.add(quantum, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 179, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Duracion del ciclo Ejec.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        NombreProceso.setText("Nombre");
        NombreProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProcesoActionPerformed(evt);
            }
        });
        jPanel2.add(NombreProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, -1));

        randomProcess.setBackground(new java.awt.Color(0, 102, 255));
        randomProcess.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        randomProcess.setForeground(new java.awt.Color(255, 255, 255));
        randomProcess.setText("Cargar Aleatorios");
        randomProcess.setBorder(null);
        randomProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomProcessActionPerformed(evt);
            }
        });
        jPanel2.add(randomProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 120, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reiniciar Proceso");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 120, 30));

        cargarDatos.setBackground(new java.awt.Color(0, 102, 255));
        cargarDatos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        cargarDatos.setText("Cargar Datos");
        cargarDatos.setBorder(null);
        cargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(cargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 120, 30));

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Guardar");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 100, 30));

        CantidadInstrucciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        CantidadInstrucciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CantidadInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 25));

        PoliticaName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PoliticaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoliticaNameActionPerformed(evt);
            }
        });
        jPanel2.add(PoliticaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 170, -1));

        TypeProcess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TypeProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeProcessActionPerformed(evt);
            }
        });
        jPanel2.add(TypeProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 170, -1));

        ciclo1.setBackground(new java.awt.Color(0, 0, 0));
        ciclo1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo1.setText("satisfacer excepcion");
        jPanel2.add(ciclo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, -1));

        ciclo2.setBackground(new java.awt.Color(0, 0, 0));
        ciclo2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo2.setText("Cantidad de ciclos para ");
        jPanel2.add(ciclo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, -1));

        ciclo3.setBackground(new java.awt.Color(0, 0, 0));
        ciclo3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ciclo3.setText("Cantidad de ciclos para ");
        jPanel2.add(ciclo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 160, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Politica");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        CyclesIO.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        CyclesIO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CyclesIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 170, 25));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 700, -1));

        IniciarProceso.setBackground(new java.awt.Color(102, 153, 255));
        IniciarProceso.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        IniciarProceso.setForeground(new java.awt.Color(255, 255, 255));
        IniciarProceso.setText("Iniciar Proceso");
        IniciarProceso.setBorder(null);
        IniciarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarProcesoActionPerformed(evt);
            }
        });
        jPanel2.add(IniciarProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 100, 30));

        Priory.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        Priory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Priory, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 60, 25));

        cargarFile.setBackground(new java.awt.Color(0, 102, 255));
        cargarFile.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cargarFile.setForeground(new java.awt.Color(255, 255, 255));
        cargarFile.setText("Subir JSON/CSV");
        cargarFile.setBorder(null);
        cargarFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFileActionPerformed(evt);
            }
        });
        jPanel2.add(cargarFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 120, 30));

        CyclesEx.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000, 1));
        CyclesEx.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(CyclesEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 170, 25));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 280));

        jPanel4.setBackground(new java.awt.Color(179, 220, 249));
        jPanel4.setFocusTraversalPolicyProvider(true);

        Listalisto.setBackground(new java.awt.Color(236, 250, 245));
        Listalisto.setPreferredSize(new java.awt.Dimension(210, 244));

        javax.swing.GroupLayout ListalistoLayout = new javax.swing.GroupLayout(Listalisto);
        Listalisto.setLayout(ListalistoLayout);
        ListalistoLayout.setHorizontalGroup(
            ListalistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        ListalistoLayout.setVerticalGroup(
            ListalistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        Listabloqueados.setBackground(new java.awt.Color(236, 250, 245));
        Listabloqueados.setPreferredSize(new java.awt.Dimension(210, 244));

        javax.swing.GroupLayout ListabloqueadosLayout = new javax.swing.GroupLayout(Listabloqueados);
        Listabloqueados.setLayout(ListabloqueadosLayout);
        ListabloqueadosLayout.setHorizontalGroup(
            ListabloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        ListabloqueadosLayout.setVerticalGroup(
            ListabloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        ListaFinalizado.setBackground(new java.awt.Color(236, 250, 245));
        ListaFinalizado.setPreferredSize(new java.awt.Dimension(210, 0));

        javax.swing.GroupLayout ListaFinalizadoLayout = new javax.swing.GroupLayout(ListaFinalizado);
        ListaFinalizado.setLayout(ListaFinalizadoLayout);
        ListaFinalizadoLayout.setHorizontalGroup(
            ListaFinalizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        ListaFinalizadoLayout.setVerticalGroup(
            ListaFinalizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Listalisto1.setBackground(new java.awt.Color(236, 250, 245));
        Listalisto1.setPreferredSize(new java.awt.Dimension(210, 244));

        javax.swing.GroupLayout Listalisto1Layout = new javax.swing.GroupLayout(Listalisto1);
        Listalisto1.setLayout(Listalisto1Layout);
        Listalisto1Layout.setHorizontalGroup(
            Listalisto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        Listalisto1Layout.setVerticalGroup(
            Listalisto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        Listo.setForeground(new java.awt.Color(102, 102, 102));
        Listo.setText("Listos");

        Bloqueados.setForeground(new java.awt.Color(102, 102, 102));
        Bloqueados.setText("Bloqueados");

        Finalizados.setForeground(new java.awt.Color(102, 102, 102));
        Finalizados.setText("Finalizados");

        Listo1.setForeground(new java.awt.Color(102, 102, 102));
        Listo1.setText("Suspendidos");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Proceso en Ejecución");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Listalisto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Listo1)
                                .addGap(102, 102, 102)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Listalisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Listo)
                                .addGap(90, 90, 90)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(Listabloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(Bloqueados)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(ListaFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Finalizados)
                                .addGap(87, 87, 87)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Listo1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Listalisto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Listo)
                            .addComponent(Bloqueados)
                            .addComponent(Finalizados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ListaFinalizado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Listabloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Listalisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 1120, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randomProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomProcessActionPerformed
           JFileChooser selarchivo = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(" Archivos JSON", "json");
        selarchivo.setFileFilter(filter);
        int val = selarchivo.showOpenDialog(null);
        if (val == JFileChooser.APPROVE_OPTION){
            if(selarchivo.getSelectedFile() != null){
            selectedFile = selarchivo.getSelectedFile();
            JOptionPane.showMessageDialog(null, "El archivo seleccionado es: " + selectedFile.getName());}
        else {
            JOptionPane.showMessageDialog(null,"Archivo no seleccionado");
        }}
    }//GEN-LAST:event_randomProcessActionPerformed

    private void cargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosActionPerformed
         if (isEmpty()){
            //SE MUESTRA UN MENSAJE DE ERROR EN CASO DE QUE NO SE HAYA SELECCIONADO NINGUN ARCHIVO
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo primero");
         }else{
             String filePath = selectedFile.getAbsolutePath();
         }
         
    }//GEN-LAST:event_cargarDatosActionPerformed
    private boolean isEmpty(){
        return selectedFile  == null;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void NombreProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProcesoActionPerformed

    private void PoliticaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoliticaNameActionPerformed
         // Obtener el algoritmo seleccionado
        String algoritmo = (String) PoliticaName.getSelectedItem();

        // Crear el nuevo planificador según el algoritmo seleccionado
        StrategyScheduler newScheduler;
        switch (algoritmo) {
            case "FCFS":
                newScheduler = StrategyScheduler.FirstComeFirstServe;
                break;
            case "SJF":
                newScheduler = StrategyScheduler.SJF;
                break;
            case "Round Robin":
                newScheduler = StrategyScheduler.RoundRobin;
                break;
            case "HRRN":
                newScheduler = StrategyScheduler.HRRN;
                break;
            case "SRT":
                newScheduler = StrategyScheduler.SRT;
                break;
            case "FB":
                newScheduler = StrategyScheduler.FB;
            default:
                JOptionPane.showMessageDialog(PanelPrincipal.this, "Algoritmo no soportado."); // Usar Simulador.this para referenciar la ventana principal
                return;
        }

    }//GEN-LAST:event_PoliticaNameActionPerformed

    private void TypeProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeProcessActionPerformed
         // Obtener el tipo de proceos seleccionado
        String typeSelect = (String) TypeProcess.getSelectedItem();
        
        // Comprobar si es I/O-Bound
        boolean esIOBound = typeSelect.equals("I/O-Bound");
        /**
         *  Asumiendo que los componentes se llaman así:
            lblCyclesExcepcion.setVisible(esIOBound);
            txtCyclesExcepcion.setVisible(esIOBound);
            lblCyclesCompleteIO.setVisible(esIOBound);
            txtCyclesCompleteIO.setVisible(esIOBound);
         */
    }//GEN-LAST:event_TypeProcessActionPerformed

    private void IniciarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarProcesoActionPerformed
        try {
        // 1. LEER DATOS EN COMUN
        String nombre = NombreProceso.getText();
        int instrucciones = (Integer) CantidadInstrucciones.getValue();
        int priory = (Integer) Priory.getValue();
        
        // 2. LEER TIPO DE PROCESO SELECCIONADO
        String TypeSelected = (String) TypeProcess.getSelectedItem();
        
        Process newProcess; // El proceso que vamos a crear
        
            // 3. DECIDIR QUÉ CONSTRUCTOR USAR
            if (TypeSelected.equals("I/O-Bound")) {
                int cyclesEx = (Integer) Priory.getValue();
                int cyclesIO = (Integer) CyclesIO.getValue();
                
            newProcess = new Process(
                nombre, 
                ProcessType.IO_BOUND,
                cyclesEx, 
                cyclesIO, 
                instrucciones, 
                priory
            ); 
        }else { // Es "CPU-Bound"
            
            newProcess = new Process(
                nombre, 
                ProcessType.CPU_BOUND,
                instrucciones, 
                priory 
            );
        }
        // Mensaje de Proceso creado correctamente 
        JOptionPane.showMessageDialog(this, "El " + nombre + " creado exitosamente.");
        
        // Limpiar los campos 
        NombreProceso.setText("");
        CantidadInstrucciones.setValue(0);
        Priory.setValue(0);
        Priory.setValue(0);
        CyclesIO.setValue(0);
        
        } catch (NumberFormatException e) {
            
        // Captura error de Formato 
        JOptionPane.showMessageDialog(this, 
            "Error: Revisa los campos numéricos.\nDeben ser números válidos.", 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);
        
        } catch (Exception e) {
            // Capturar cualquier otro error 
             JOptionPane.showMessageDialog(this, 
                "Ocurrió un error: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IniciarProcesoActionPerformed

    private void cargarFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bloqueados;
    private javax.swing.JSpinner CantidadInstrucciones;
    private javax.swing.JSpinner CyclesEx;
    private javax.swing.JSpinner CyclesIO;
    private javax.swing.JLabel Finalizados;
    private javax.swing.JButton IniciarProceso;
    private java.awt.Panel ListaFinalizado;
    private java.awt.Panel Listabloqueados;
    private java.awt.Panel Listalisto;
    private java.awt.Panel Listalisto1;
    private javax.swing.JLabel Listo;
    private javax.swing.JLabel Listo1;
    private javax.swing.JTextField NombreProceso;
    private javax.swing.JComboBox<String> PoliticaName;
    private javax.swing.JSpinner Priory;
    private javax.swing.JSpinner Spinnerciclo;
    private javax.swing.JComboBox<String> TypeProcess;
    private javax.swing.JButton cargarDatos;
    private javax.swing.JButton cargarFile;
    private javax.swing.JLabel ciclo;
    private javax.swing.JLabel ciclo1;
    private javax.swing.JLabel ciclo2;
    private javax.swing.JLabel ciclo3;
    private javax.swing.JLabel instrucciones;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel quantum;
    private javax.swing.JButton randomProcess;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
